### ISSUE TITLE
Not found in npm registry

### ISSUE THREAD

**Issue by JanIHC** [deliverr/knex-snowflake-dialect#9]
Hi,

I get a 'not found' error when I try to install your package

```
PS C:\Repositories\xxdssfg> npm install knex-snowflake-client
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/knex-snowflake-client - Not found
```

**Comment by emurphy** [comment]
Very strange, but that is unlikely to be a problem with the `knex-snowflake-dialect` package specifically. Others are able to install it from npm.

**Comment by adibro500** [comment]
Same here. Not found on npm registry.

**Comment by emurphy** [comment]
The problem was due to a mistake in the README.md. The npm package is named `knex-snowflake-dialect`, not `knex-snowflake-client`. Thanks to @mingp for the observation in #10
